### PR TITLE
Do not explicitly set user home

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by fabiocos** [comment]
@smuzaffar is this addressing the general case of ```$HOME``` directories with different names (like in lxplus) ?

**Comment by smuzaffar** [comment]
@fabiocos , Christoph Wissing noticed that script does not work[a] with singularity 3.4.x version due to user home explicitly set. Looks like internally sigunlarity properly use home directory. I have tested this change with singularity 3.5.3 and 3.6.1 and works properly.

Can you give it a try too? All you need is to do
```
wget https://raw.githubusercontent.com/cms-sw/cmssw-osenv/c21354e8504c3baf1376ad508ea05895adcce05e/cmssw-env
chmod +x cmssw-env
./cmssw-env --cmsos slc6
```

[a]
```
>  /cvmfs/cms.cern.ch/common/cmssw-slc6 --command-to-run sleep 10
FATAL:   container creation failed: mount
->/var/singularity/mnt/session/home/username error: can't remount
/var/singularity/mnt/session/home/username: invalid argument
```

**Comment by fabiocos** [comment]
@smuzaffar it looks to me it is ok, thanks for the clarification:

```
10:18 lxplus784 500> cd /tmp/fabiocos/
10:18 lxplus784 501> ls -a
./  ../
10:18 lxplus784 502> wget https://raw.githubusercontent.com/cms-sw/cmssw-osenv/c21354e8504c3baf1376ad508ea05895adcce05e/cmssw-env
--2020-08-06 10:18:17--  https://raw.githubusercontent.com/cms-sw/cmssw-osenv/c21354e8504c3baf1376ad508ea05895adcce05e/cmssw-env
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3345 (3.3K) [text/plain]
Saving to: ‘cmssw-env’

100%[========================================================================================================================================>] 3,345       --.-K/s   in 0s      

2020-08-06 10:18:17 (38.6 MB/s) - ‘cmssw-env’ saved [3345/3345]

10:18 lxplus784 503> chmod +x cmssw-env
10:18 lxplus784 504> ./cmssw-env --cmsos slc6
08:18 lxplus784 500> cd $HOME ; pwd
/afs/cern.ch/user/f/fabiocos
```

**Comment by smuzaffar** [comment]
thanks for checking @fabiocos

**Comment by chwissing** [comment]
As discussed via e-mail, with Singularity 3.4 one needs to add --contain as option. It works with AFS Home directory.
Nevertheless DESY upgraded to Singularity 3.6 actually today and cmssw-env now works with present version and with this patch.
So I have no strong preference how you deal with it. All in all things can be a bit fragile, since Singularity changes its behaviour from time to time and we have almost no control, what version people have installed locally.
Anyway thanks a lot for your prompt efforts!

**Comment by smuzaffar** [comment]
thanks @chwissing for the feedback. I would still like to drop the options pass to singularity via cmssw-env (e.g. --home path). This will allow users to override/add extra options for singularity. As discussed in the e-mail, `--contain` works for `/afs` home directories as `cmssw-env` explicitly mounts `/afs` but it does not work if user home is on some other disk e.g. `/home/username` (in this case the `/home/username`  is empty inside singularity env).

**Pull request merged**
